#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'Resources', url: 'pages/resources.html'}
- {name: 'Podcast', url: 'pages/podcast.html'}
- {name: 'About', url: 'pages/about.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Javier Orraca data science scatter data podcast beginner resources personal portfolio powered by GitHub'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: 'UA-127790709-1'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# Work Section

projects:
- {name: 'Unsupervised Machine Learning: Part 1/2 (Clustering)', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Unsupervised Machine Learning: Part 2/2 (Clustering done... Now what?!?)', folder: 'proj-2', file: 'projects/proj-2.html'}
#- {name: 'Tools & Tips from DataScienceGO 2018', folder: 'proj-3', file: 'projects/proj-3.html'}
#- {name: 'Project Four', folder: 'proj-4', file: 'projects/proj-4.html'}
#- {name: 'Project Five', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'https://twitter.com/Scatter_Podcast'}
- {icon: 'instagram', link: 'https://www.instagram.com/iwantmorejavier/'}
- {icon: 'github', link: 'https://javorraca.github.io/Home'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/orraca/'}
- {icon: 'envelope', link: 'mailto:orraca.javier@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
