#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'Resources', url: 'pages/resources.html'}
- {name: 'Scatter', url: 'pages/scatter.html'}
- {name: 'About', url: 'pages/about.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Javier Orraca data science scatter data podcast beginner resources personal portfolio powered by GitHub'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: |
  #### About
  Hi folks, my name is Javier and I am a Business Analytics masters student at the University of California, Irvine. This new STEM-certified Masters of Science degree is a hybrid business and data science program enabling us to support the digitally driven world we share.
  
  My career includes over a decade of experience in data analysis and financial modeling for EY, Pacific Gas & Electric (PG&E), and KPMG, supporting the M&A deal cycle, corporate finance, and internal and external stakeholders. I can confidently say that I've never been more excited and passionate about a career pivot... Advanced statistical analyses, data visualizations, machine learning, and artificial intelligence, this is very much a thing of TODAY and I can't wait to make a difference with the conceptual knowledge and technical skills that I am gaining.
  
  While this site is an obvious shameless plug for my projects and interests, I also want it to be a community repository of solid resources and career information for anyone interested in data science (students, beginners, practitioners, business managers, etc.). I'll continuously build up the Resources page and Scatter Data Podcast will be launched soon, both of which are designed to provide more insight into the topics of business intelligence, data science, programming, machine learning, and data visualizations.
  
  The easiest way to contact me is [through my email](mailto:orraca.javier@gmail.com) or [via LinkedIn](https://www.linkedin.com/in/orraca/) if you have any questions or want to collaborate.

<footer>
  <div class="footer-wrap">
    <div class="footer-tagline">
      <p></p>
    </div>
    <div class="social-media">
      <nav>
        
          <a href="#" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a>
        
          <a href="#" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a>
        
          <a href="#" target="_blank"><i class="fa fa-github" aria-hidden="true"></i></a>
        
          <a href="#" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
        
          <a href="mailto:#" target="_blank"><i class="fa fa-envelope" aria-hidden="true"></i></a>
        
      </nav>
    </div>
  </div>
</footer>
#-------------------------------
# Work Section

projects:
- {name: 'Project One', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Project Two', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'Project Three', folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: 'Project Four', folder: 'proj-4', file: 'projects/proj-4.html'}
- {name: 'Project Five', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'https://twitter.com/Scatter_Podcast'}
- {icon: 'instagram', link: 'https://www.instagram.com/iwantmorejavier/'}
- {icon: 'github', link: 'https://javorraca.github.io/Home'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/orraca/'}
- {icon: 'envelope', link: 'mailto:orraca.javier@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
